services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: mylo
      POSTGRES_USER_FILE: /run/secrets/db_user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_password
      - db_user

secrets:
  db_password:
    file: docker-secrets/db_password.txt
  db_user:
    file: docker-secrets/db_user.txt

volumes:
  pgdata:
